In [1]:
import torch
import torch.nn as nn

In [7]:
fc = nn.Linear(20, 30)
input = torch.randn(128, 20)
output = fc(input)
print(output.size())

torch.Size([128, 30])


In [3]:
k = torch.asarray([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(k.transpose(-2, -1))

tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])


In [39]:
qW = nn.Linear(768, 64)
kW = nn.Linear(768, 64)
vW = nn.Linear(768, 64)
input = torch.randn(2, 768)
q = qW(input)
k = kW(input)
v = vW(input)
weight = q @ k.transpose(-2, -1)
print(weight)
print(v)
print(weight @ v)

tensor([[ 0.9470, -4.0875],
        [-1.4447,  4.3595]], grad_fn=<MmBackward0>)
tensor([[-0.2521,  0.6759, -0.2641, -0.1350, -0.2911, -0.0828, -0.6873,  0.3205,
          0.2366, -1.2433, -0.0175, -0.3074,  0.6252, -0.2621,  0.3056, -0.7292,
          0.1822,  0.2033, -0.3802,  0.1734, -0.6195, -0.7679, -0.7985,  0.0438,
          0.0987,  1.0873,  0.4902, -0.1848, -0.0928, -1.5392,  0.0974,  0.0969,
         -1.6250, -1.0636,  1.3841,  1.0922, -0.6449,  0.8363, -0.3927, -0.5895,
          0.0774, -0.2512,  0.1293,  1.0242,  0.0824,  1.0435,  1.4922, -0.9426,
         -0.0851, -0.6728,  0.6973, -1.3030, -0.1979, -0.5466,  0.1747,  0.1176,
         -0.9902, -0.3825,  0.0143, -0.2128, -0.2039,  0.3176,  0.9815, -0.1284],
        [ 0.5579, -0.0644,  0.1011, -0.1774, -0.1765, -1.3531, -0.5546, -0.2020,
         -0.0057, -0.1395,  0.4341, -0.1604,  0.7103, -0.2848,  0.7015,  0.0143,
         -0.3195, -0.7684,  0.4214, -0.0302,  0.4212,  0.1067, -0.7364,  0.5278,
          0.5720,  0.4324, -

In [27]:
print(torch.tril(torch.ones(3, 3)))

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])


In [44]:
print(torch.ones(3, 3).shape)
bsz, seq_len = torch.ones(3, 4).shape
print(bsz)
print(seq_len)

torch.Size([3, 3])
3
4


In [50]:
tensor = torch.asarray([[[1, 2, 3]], [[1, 2, 3]]])
bsz, seq_len, _ = tensor.shape
print(bsz)
print(seq_len)
print(_)

2
1
3


In [56]:
# 创建一个一维张量
a1 = torch.arange(0, 16)
print(a1)

# 使用-1让PyTorch自动计算维度
a2 = a1.view(-1, 16)
a3 = a1.view(-1, 8)
a4 = a1.view(-1, 4)
a5 = a1.view(-1, 2)
print(a2)
print(a3)
print(a4)
print(a5)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])


In [60]:
x = torch.ones((3, 4))
head_shape = x.shape[:-1]
print(head_shape)

3 3


In [69]:

# 原始张量
x = torch.randn(24, 512)  # 形状: [24, 512]
print(f"原始形状: {x.shape}")

seq_len = 6
batch_size = 4

# 重塑操作
x = x.reshape(seq_len, batch_size, -1)
print(f"重塑后形状: {x.shape}")  # [6, 4, 128]

原始形状: torch.Size([24, 512])
重塑后形状: torch.Size([6, 4, 512])


In [70]:
A = torch.randn(3, 4)
B = torch.randn(4, 5)
C = torch.einsum('ab,bc->ac', A, B)
print(C)

tensor([[-0.5179,  1.8537, -0.3126,  0.2462, -2.7441],
        [-2.2057,  0.3483, -2.9811,  0.2237,  1.8530],
        [-0.3114,  0.0248, -5.9422, -2.8632,  1.5514]])
