In [110]:
import torch
import torch.nn as nn

In [111]:
inputs = torch.tensor(
    [
        [0.43, 0.15, 0.89],  # Your(x^1)
        [0.55, 0.87, 0.66],  # journey(x^2)
        [0.57, 0.85, 0.64],  # starts(x^3)
        [0.22, 0.58, 0.33],  # with(x^4)
        [0.77, 0.25, 0.10],  # one(x^5)
        [0.65, 0.80, 0.55],  # step(x^6)
    ]
)

In [112]:
query = inputs[1]
attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)
print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.4165])


In [113]:
res = 0
for idx, element in enumerate(inputs[0]):
    res += inputs[0][idx] * query[idx]
print(res)
print(torch.dot(inputs[0], query))

tensor(0.9544)
tensor(0.9544)


In [114]:
attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()
print("Attention weights:", attn_weights_2_tmp)
print("Sum:", attn_weights_2_tmp.sum())

Attention weights: tensor([0.1385, 0.2169, 0.2141, 0.1224, 0.1026, 0.2055])
Sum: tensor(1.0000)


In [115]:
def softmax_native(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)
attn_weights_2_native = softmax_native(attn_scores_2)
print("Attention weights:", attn_weights_2_native)
print("Sum:", attn_weights_2_native.sum())

Attention weights: tensor([0.1305, 0.2240, 0.2197, 0.1168, 0.1019, 0.2071])
Sum: tensor(1.)


In [116]:
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print("Attention weights:", attn_weights_2)
print("Sum:", attn_weights_2.sum())

Attention weights: tensor([0.1305, 0.2240, 0.2197, 0.1168, 0.1019, 0.2071])
Sum: tensor(1.)


In [117]:
attn_scores = torch.empty(6,6)
for i,x_i in enumerate(inputs):
    for j,x_j in enumerate(inputs):
        attn_scores[i,j] = torch.dot(x_i,x_j)
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.8890],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.4165],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.4025],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.7885],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.7555],
        [0.8890, 1.4165, 1.4025, 0.7885, 0.7555, 1.3650]])


In [118]:
attn_scores = inputs @ inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.8890],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.4165],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.4025],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.7885],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.7555],
        [0.8890, 1.4165, 1.4025, 0.7885, 0.7555, 1.3650]])


In [119]:
attn_weights = torch.softmax(attn_scores, dim=-1)
print(attn_weights)

tensor([[0.2012, 0.1924, 0.1900, 0.1191, 0.1170, 0.1802],
        [0.1305, 0.2240, 0.2197, 0.1168, 0.1019, 0.2071],
        [0.1307, 0.2227, 0.2187, 0.1168, 0.1042, 0.2071],
        [0.1401, 0.2025, 0.1997, 0.1427, 0.1233, 0.1917],
        [0.1418, 0.1820, 0.1835, 0.1270, 0.1746, 0.1910],
        [0.1290, 0.2185, 0.2155, 0.1166, 0.1128, 0.2076]])


In [120]:
print("all row sums:",attn_weights.sum(dim=-1))

all row sums: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [121]:
print(attn_weights.shape)
print(inputs.shape)
all_context_vecs = attn_weights @ inputs
print(all_context_vecs)

torch.Size([6, 6])
torch.Size([6, 3])
tensor([[0.5341, 0.6016, 0.5778],
        [0.5433, 0.6601, 0.5672],
        [0.5438, 0.6586, 0.5660],
        [0.5364, 0.6339, 0.5510],
        [0.5522, 0.6058, 0.5283],
        [0.5459, 0.6545, 0.5608]])


In [122]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
print(query_2)

tensor([0.4306, 1.4551])


In [123]:
querys = inputs @ W_query
keys = inputs @ W_key
values = inputs @ W_value
attn_scores_2 = querys[1] @ keys.T
print("keys.shape",keys.shape)
print("values.shape",values.shape)
print("scores:",attn_scores_2)

keys.shape torch.Size([6, 2])
values.shape torch.Size([6, 2])
scores: tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.6687])


In [124]:
d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5,dim=-1)
print(attn_weights_2)

tensor([0.1475, 0.2226, 0.2162, 0.1289, 0.0891, 0.1955])


In [125]:
context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

tensor([0.3152, 0.8435])


In [126]:
class SelfAttention_v1(nn.Module):
    def __init__(self, d_int, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_int, d_out))
        self.W_key = nn.Parameter(torch.rand(d_int, d_out))
        self.W_value = nn.Parameter(torch.rand(d_int, d_out))

    def forward(self, x):
        keys = x @ self.W_key
        queries = x @ self.W_query
        values = x @ self.W_value
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=-1)
        context_vec = attn_weights @ values
        return context_vec

In [128]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in,d_out)
print(sa_v1(inputs))

tensor([[0.3084, 0.8274],
        [0.3152, 0.8435],
        [0.3149, 0.8428],
        [0.3034, 0.8155],
        [0.3012, 0.8105],
        [0.3138, 0.8403]], grad_fn=<MmBackward0>)


In [139]:
class SelfAttention_v2(nn.Module):
    def __init__(self, d_int, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_int, d_out, qkv_bias)
        self.W_key = nn.Linear(d_int, d_out, qkv_bias)
        self.W_value = nn.Linear(d_int, d_out, qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=-1)
        context_vec = attn_weights @ values
        return context_vec

In [140]:
torch.manual_seed(123)
sa_v2 = SelfAttention_v2(d_in,d_out)
print(sa_v2(inputs))

tensor([[-0.5825, -0.1176],
        [-0.5820, -0.1201],
        [-0.5820, -0.1200],
        [-0.5792, -0.1192],
        [-0.5803, -0.1185],
        [-0.5819, -0.1199]], grad_fn=<MmBackward0>)


In [149]:
queries = sa_v2.W_query(inputs)
keys = sa_v2.W_key(inputs)
attn_scores = queries @ keys.T
print(attn_scores)
attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=-1)
print(attn_weights)

tensor([[0.3111, 0.3479, 0.3471, 0.1714, 0.2350, 0.3441],
        [0.1655, 0.2602, 0.2576, 0.1445, 0.1384, 0.2505],
        [0.1667, 0.2602, 0.2577, 0.1443, 0.1391, 0.2507],
        [0.0510, 0.1080, 0.1064, 0.0643, 0.0476, 0.1022],
        [0.1415, 0.1875, 0.1863, 0.0987, 0.1121, 0.1828],
        [0.1643, 0.2554, 0.2529, 0.1414, 0.1369, 0.2461]],
       grad_fn=<MmBackward0>)
tensor([[0.1687, 0.1731, 0.1730, 0.1528, 0.1598, 0.1726],
        [0.1622, 0.1734, 0.1731, 0.1598, 0.1591, 0.1723],
        [0.1623, 0.1734, 0.1731, 0.1598, 0.1592, 0.1722],
        [0.1633, 0.1700, 0.1698, 0.1648, 0.1629, 0.1693],
        [0.1654, 0.1709, 0.1708, 0.1605, 0.1620, 0.1703],
        [0.1625, 0.1733, 0.1730, 0.1598, 0.1593, 0.1721]],
       grad_fn=<SoftmaxBackward0>)


In [155]:
masked_simple = attn_weights *torch.tril(torch.ones(attn_weights.shape))
print(masked_simple)
row_sums = masked_simple.sum(dim=-1, keepdim=True)
print(row_sums)
masked_simple_norm = masked_simple / row_sums
print(masked_simple_norm)

tensor([[0.1687, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1622, 0.1734, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1623, 0.1734, 0.1731, 0.0000, 0.0000, 0.0000],
        [0.1633, 0.1700, 0.1698, 0.1648, 0.0000, 0.0000],
        [0.1654, 0.1709, 0.1708, 0.1605, 0.1620, 0.0000],
        [0.1625, 0.1733, 0.1730, 0.1598, 0.1593, 0.1721]],
       grad_fn=<MulBackward0>)
tensor([[0.1687],
        [0.3357],
        [0.5088],
        [0.6678],
        [0.8297],
        [1.0000]], grad_fn=<SumBackward1>)
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4833, 0.5167, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3190, 0.3408, 0.3402, 0.0000, 0.0000, 0.0000],
        [0.2445, 0.2545, 0.2542, 0.2468, 0.0000, 0.0000],
        [0.1994, 0.2060, 0.2058, 0.1935, 0.1953, 0.0000],
        [0.1625, 0.1733, 0.1730, 0.1598, 0.1593, 0.1721]],
       grad_fn=<DivBackward0>)


In [171]:
mask = torch.triu(torch.ones(attn_weights.shape), diagonal=1)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked)
attn_weights = torch.softmax(masked / keys.shape[-1] ** 0.5, dim=1)
print(attn_weights)
context_vec = attn_weights @ values
print(context_vec)

tensor([[0.3111,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.1655, 0.2602,   -inf,   -inf,   -inf,   -inf],
        [0.1667, 0.2602, 0.2577,   -inf,   -inf,   -inf],
        [0.0510, 0.1080, 0.1064, 0.0643,   -inf,   -inf],
        [0.1415, 0.1875, 0.1863, 0.0987, 0.1121,   -inf],
        [0.1643, 0.2554, 0.2529, 0.1414, 0.1369, 0.2461]],
       grad_fn=<MaskedFillBackward0>)
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4833, 0.5167, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3190, 0.3408, 0.3402, 0.0000, 0.0000, 0.0000],
        [0.2445, 0.2545, 0.2542, 0.2468, 0.0000, 0.0000],
        [0.1994, 0.2060, 0.2058, 0.1935, 0.1953, 0.0000],
        [0.1625, 0.1733, 0.1730, 0.1598, 0.1593, 0.1721]],
       grad_fn=<SoftmaxBackward0>)
tensor([[0.1855, 0.8812],
        [0.2938, 0.9445],
        [0.3258, 0.9576],
        [0.3036, 0.8564],
        [0.2737, 0.7564],
        [0.2910, 0.7839]], grad_fn=<MmBackward0>)


In [174]:
batch = torch.stack((inputs, inputs), dim=0)
print(batch.shape)

torch.Size([2, 6, 3])


In [191]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            "mask", torch.triu(torch.ones(context_length, context_length), diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.transpose(1, 2)
        attn_scores.masked_fill(self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)
        attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim=-1)
        attn_weights = self.dropout(attn_weights)
        print(attn_weights.shape)
        context_vec = attn_weights @ values
        return context_vec

In [192]:
ca = CausalAttention(3,2,6,0.1)
print(ca(batch).shape)

torch.Size([2, 6, 6])
torch.Size([2, 6, 2])


In [193]:
class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout, num_heads, qkv_bias=False):
        super().__init__()
        self.heads = nn.ModuleList(
            [
                CausalAttention(d_in, d_out, context_length, dropout, qkv_bias)
                for _ in range(num_heads)
            ]
        )

    def forward(self, x):
        return torch.cat([head(x) for head in self.heads], dim=-1)

In [199]:
mha = MultiHeadAttentionWrapper(
    d_in, d_out, 6, 0.0, num_heads=2, qkv_bias=False
)
context_vecs = mha(batch)
print(context_vecs)
print(context_vecs.shape)

torch.Size([2, 6, 6])
torch.Size([2, 6, 6])
tensor([[[-0.2277, -0.2667, -0.4231,  0.0987],
         [-0.2292, -0.2648, -0.4211,  0.0975],
         [-0.2291, -0.2648, -0.4212,  0.0975],
         [-0.2338, -0.2621, -0.4209,  0.0970],
         [-0.2299, -0.2645, -0.4233,  0.0982],
         [-0.2289, -0.2649, -0.4215,  0.0976]],

        [[-0.2277, -0.2667, -0.4231,  0.0987],
         [-0.2292, -0.2648, -0.4211,  0.0975],
         [-0.2291, -0.2648, -0.4212,  0.0975],
         [-0.2338, -0.2621, -0.4209,  0.0970],
         [-0.2299, -0.2645, -0.4233,  0.0982],
         [-0.2289, -0.2649, -0.4215,  0.0976]]], grad_fn=<CatBackward0>)
torch.Size([2, 6, 4])
